# Generated by Django 3.2.25 on 2024-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='url',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
