# Generated by Django 3.2.25 on 2024-07-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_menus_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('student_id', models.CharField(default='', max_length=11)),
                ('fathers_name', models.CharField(default='', max_length=50)),
                ('fathers_mobile', models.CharField(default='', max_length=50)),
                ('mothers_name', models.CharField(default='', max_length=50)),
                ('birth_date', models.DateField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('admission_fee', models.FloatField(default=0)),
                ('others_fee', models.FloatField(default=0)),
                ('total_mark', models.FloatField(default=0)),
                ('present_address', models.CharField(max_length=256)),
                ('parmanent_address', models.CharField(max_length=256)),
                ('stu_status', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='')),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapp.studentclass')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapp.gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapp.studentgrade')),
            ],
        ),
    ]
