# Generated by Django 5.0.7 on 2024-07-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0003_admission_gender_studentclass_studentgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuhomeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('files', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='stunotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjecteight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjectnine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjectseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjectsix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjectten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptions', models.TextField()),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachereducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=12)),
                ('teacher_name', models.CharField(blank=True, max_length=250, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=250, null=True)),
                ('institute_Code', models.CharField(blank=True, max_length=12, null=True)),
                ('department_name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('admission_date', models.DateField()),
                ('final_exam_date', models.DateField()),
                ('result', models.CharField(blank=True, max_length=25)),
                ('registration', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'teachereducation',
                'verbose_name_plural': 'Teacher Education Table',
            },
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'Admission', 'verbose_name_plural': 'Student Admission Table'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender', 'verbose_name_plural': 'Gender Table'},
        ),
        migrations.AddField(
            model_name='admission',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='full_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='admission',
            name='institute',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admission',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='teacherregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('full_name', models.CharField(default='', max_length=256)),
                ('password', models.CharField(max_length=500)),
                ('teacher_id', models.CharField(default='', max_length=11)),
                ('fathers_name', models.CharField(default='', max_length=50)),
                ('fathers_mobile', models.CharField(default='', max_length=50)),
                ('mothers_name', models.CharField(default='', max_length=50)),
                ('birth_date', models.DateField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('present_address', models.CharField(max_length=256)),
                ('parmanent_address', models.CharField(max_length=256)),
                ('tea_status', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapp.gender')),
            ],
            options={
                'verbose_name': 'stuadmission',
                'verbose_name_plural': 'Student Admission Table',
            },
        ),
    ]
